djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from leads.views import LandingTemplateView, SignupView
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", LandingTemplateView.as_view(), name="landing"),
    path("leads/", include("leads.urls", namespace="leads")),
    path("agents/", include("agents.urls", namespace="agents")),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", SignupView.as_view(), name="signup"),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from .views import (
    home, lead_detail, lead_create, lead_update, lead_delete,
    LeadDetailView, LeadCreateView, LeadDeleteView, LeadUpdateView, LeadListView,
)


app_name = "leads"

urlpatterns = [
    path("", LeadListView.as_view(), name="lead_list"),
    path("<int:pk>/", LeadDetailView.as_view(), name="lead_detail"),
    path("update/<int:pk>/", LeadUpdateView.as_view(), name="lead_update"),
    path("create/", LeadCreateView.as_view(), name="lead_create"),
    path("delete/<int:pk>/", LeadDeleteView.as_view(), name="lead_delete"),
]

leads/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser
from django.db.models.fields.related import OneToOneField


class User(AbstractUser):
    pass


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.username

class Lead(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email = models.EmailField(max_length=50)
    phone_number = models.CharField(max_length=15)
    age = models.IntegerField(default=0)
    agent = models.ForeignKey("Agent", on_delete=models.SET_DEFAULT, default="Unassigned")

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Agent(models.Model):
    name = models.OneToOneField(User, on_delete=models.CASCADE)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.name.username


def post_user_created_signal(sender, instance, created, **kwargs):
    print(instance, created)
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(post_user_created_signal, sender=User)

leads/forms.py
from django import forms 
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from .models import Lead, Agent

User = get_user_model()

class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'first_name',
            'last_name',
            'email',
            'age',
            'agent'
        )


class LeadForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()
    age = forms.IntegerField(min_value=0)


class CustomUserCreationForm(UserCreationForm):
    class Meta:

        model = User
        fields = ("username",)
        field_classes = {"username": UsernameField}

leads/views.py
from django.core.mail import send_mail
from django.shortcuts import render, redirect, reverse
from django.views.generic import TemplateView, CreateView, UpdateView, DeleteView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Lead, Agent
from .forms import LeadForm, LeadModelForm, CustomUserCreationForm


class SignupView(CreateView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse("login")


class LandingTemplateView(TemplateView):
    # TODO render the home page
    template_name = "landing.html"


def landing(request):
    return render(request, "landing.html")


class LeadListView(LoginRequiredMixin, ListView):
    template_nanme = "leads/lead_list.html"
    queryset = Lead.objects.all()
    context_object_name = "leads"



def home(request):
    leads = Lead.objects.all()

    context = {"leads":leads}
    return render(request, "leads/lead_list.html", context)


class LeadDetailView(LoginRequiredMixin, DetailView):
    template_name = "leads/lead_detail.html"
    queryset = Lead.objects.all()
    context_object_name = "lead"


def lead_detail(request, pk):
    lead = Lead.objects.get(id=pk)

    context = {'lead':lead}
    return render(request, "leads/lead_detail.html", context)


class LeadCreateView(LoginRequiredMixin, CreateView):
    template_name = "leads/lead_create.html"
    form_class = LeadModelForm
    
    def get_success_url(self):
        return reverse("leads:lead_list")

    def  form_valid(self, form):
        # TODO send email
        send_mail(
            subject="A lead has been created",
            message="Go to the site to see the new lead",
            from_email="test@test.com",
            recipient_list=["test2@test.com"]
        )
        return super(LeadCreateView, self).form_valid(form)



def lead_create(request):
    form = LeadModelForm()
    if request.method == "POST":
        print("Recieving a post request")
        form = LeadModelForm(request.POST)
        if form.is_valid():
            print("This form is valid")
            form.save()
            return redirect('/leads')

    context = {
        "form":form
        }

    return render(request, "leads/lead_create.html", context)


class LeadUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "leads/lead_update.html"
    form_class = LeadModelForm
    queryset = Lead.objects.all()
    context_object_name = "lead"

    def get_success_url(self):
        return reverse("leads:lead_list")


def lead_update(request, pk):
    lead = Lead.objects.get(id=pk)
    form = LeadModelForm(instance=lead)
    if request.method == "POST":
        print("Recieving a posr request")
        form = LeadModelForm(request.POST, instance=lead)
        if form.is_valid():
            print("This form is valid")
            form.save()
            return redirect('/leads')

    context = {
        "form":form,
        "lead":lead,
        }

    return render(request, "leads/lead_update.html", context)


class LeadDeleteView(LoginRequiredMixin, DeleteView):
    template_name = "leads/lead_delete.html"
    queryset = Lead.objects.all()
    context_object_name = "lead"

    def get_success_url(self):
        return reverse("leads:lead_list")


def lead_delete(request, pk):
    lead = Lead.objects.get(id=pk)
    if request.method == "POST":
        lead.delete()
        return redirect('/leads')
    context = {
        "lead":lead
    }
    return render(request, "leads/lead_delete.html", context)

"""def lead_create(request):
    form = LeadForm()
    if request.method == "POST":
        print("Recieving a posr request")
        form = LeadForm(request.POST)
        if form.is_valid():
            print("This form is valid")
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            age = form.cleaned_data['age']
            agent = Agent.objects.first()
            Lead.objects.create(
                first_name=first_name,
                last_name=last_name,
                age = age,
                email = email,
                agent = agent
            )
            return redirect('/leads')

    context = {
        "form":form
        }

    return render(request, "leads/lead_create.html", context)"""

leads/templates/leads/home.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h1>There is literally nothing to be afarid of here This is the home oage by the way</hq>
        <script src="" async defer></script>
    </body>
</html>

leads/templates/leads/lead_create.html
{% extends "base.html" %}

{% block title %}
 
Updating lead

{% endblock title %}

{% block content %}
    <h3><a href="{% url "leads:lead_list" %}">Go back</a </h3>
    <hr>
    <h1>Create a lead</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" >Create Lead</button>
    </form>
        
{% endblock %}

leads/templates/leads/lead_delete.html
{% extends "base.html" %}

{% block title %}
 
Delete lead

{% endblock title %}

{% block content %}
    <h3><a href="{% url "leads:lead_list" %}">Go back</a </h3>
    <hr>
    <h1>Are you sure you want to Delete {{ lead.first_name }}</h1>
    <form method="post">
        {% csrf_token %}
        <a href="{% url "leads:lead_list" %}">Cancel</a>
        <button type="submit" >Delete Lead</button>
    </form> 
        
{% endblock %}

leads/templates/leads/lead_detail.html
{% extends "base.html" %}
{% block title %}
 
Updating lead

{% endblock title %}

{% block content %}
    <section class="text-gray-600 body-font">
        <div class="container px-5 py-24 mx-auto flex flex-wrap">
            <div class="flex flex-wrap -mx-4 mt-auto mb-auto lg:w-1/2 sm:w-2/3 content-start sm:pr-10">
            <div class="w-full sm:p-4 px-4 mb-6">
                <h1 class="title-font font-medium text-xl mb-2 text-gray-900">Name : {{ lead.first_name }} {{ lead.last_name }}</h1>
                <h1 class="title-font font-medium text-xl mb-2 text-gray-900">Age : {{ lead.age }}</h1>
                <h1 class="title-font font-medium text-xl mb-2 text-gray-900">Email : {{ lead.email }}</h1>
                <h1 class="title-font font-medium text-xl mb-2 text-gray-900">Phone Number : {{ lead.phone_number }}</h1>
                <div class="leading-relaxed">Description: There is nohing to see here for now</div>
            </div>
            <div class="p-4 sm:w-1/2 lg:w-1/4 w-1/2">
                <a href="{% url "leads:lead_update" lead.pk %}">
                    <button class="flex-shrink-0 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg mt-10 sm:mt-0">Update</button>
                </a>
            </div>
            <div class="p-4 sm:w-1/2 lg:w-1/4 w-1/2">
                <a href="{% url "leads:lead_delete" lead.pk %}">
                    <button class="flex-shrink-0 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg mt-10 sm:mt-0">Delete</button>
                </a>
            </div>
            </div>
            <div class="lg:w-1/2 sm:w-1/3 w-full rounded-lg overflow-hidden mt-6 sm:mt-0">
            <img class="object-cover object-center w-full h-full" src="https://dummyimage.com/600x300" alt="stats">
            </div>
        </div>
    </section>



    <h1> Lead detail  <h3>  <a href="{% url 'leads:lead_list' %}">Go back</a </h3> | <a href="{% url 'leads:lead_update' lead.pk %}">Update</a> </h1>
    
    <hr>
{% endblock %}

leads/templates/leads/lead_list.html
{% extends "base.html" %}
{% block title %}
 
Lead List
{% endblock title %}

{% block content %}


<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div class="w-full mb-5 flex justify-between items-center border-b border-gray-200">
        <div>
            <h1 class="text-4xl text-gray-800">Leads</h1>
        </div>
        <div>
            <a href="{% url 'leads:lead_create'  %}"> Create Lead</a>
        </div>
    </div>
  
    <hr />
    <div class="flex flex-wrap -m-4">
      {% for lead in leads %}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10" viewBox="0 0 24 24">
              <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
              <circle cx="12" cy="7" r="4"></circle>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{ lead.first_name }} {{ lead.last_name }}</h2>
            <p class="leading-relaxed text-base">A short description abour the lead</p>
            <a href="{% url "leads:lead_detail" lead.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">View Lead
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
      
    </div>
  </div>
</section>


        <h1> Leads List <h3><a href="{% url 'leads:lead_create'  %}"> Create Lead</a </h3></h1>
        <ul>
            {% for lead in leads %}
                <li>
                    <a href="{% url 'leads:lead_detail' lead.pk %}">{{ lead }}</a> -
                    <a href="{% url 'leads:lead_update' lead.pk %}">Update</a> |
                    <a href="{% url 'leads:lead_delete' lead.pk %}">Delete</a> 
                </l1>
            {% endfor %}
        </ul>
{% endblock %}
        

leads/templates/leads/lead_update.html
{% extends "base.html" %}
 {% block title %}
 
Updating lead

 {% endblock title %}

 {% block content %}

    <h3><a href="{% url 'leads:lead_list' %}">Go back</a </h3>
    <hr>
    <h1>Update a lead</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" >Update Lead</button>
    </form>
 
 {% endblock content %}

        
        
       