agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView


app_name = "agents"

urlpatterns = [
    path("", AgentListView.as_view(), name='agents'),
    path('create/', AgentCreateView.as_view(), name="agent_create"),

    

]

djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from leads.views import LandingTemplateView, SignupView
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", LandingTemplateView.as_view(), name="landing"),
    path("leads/", include("leads.urls", namespace="leads")),
    path("agents/", include("agents.urls", namespace="agents")),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", SignupView.as_view(), name="signup"),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms
from django.forms import fields
from leads.models import Agent


class AgentModelForm(forms.ModelForm):
    class Meta:
        model = Agent
        fields = (
            'name',
        )

agents/views.py
from typing import List
from django.shortcuts import reverse
from django.views.generic import ListView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from leads.models import Agent
from .forms import AgentModelForm


class AgentListView(LoginRequiredMixin, ListView):
    template_name = "agents/agent_list.html"

    def get_queryset(self):
        return Agent.objects.all()


class AgentCreateView(LoginRequiredMixin, CreateView):
    template_name = "agents/agent_create.html"
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse("agents:agents")

    def form_valid(self, form):
        agent = form.save(commit=False)
        agent.organisation = self.request.user.userprofile
        agent.save()
        return super(AgentCreateView, self).form_valid(form)

agents/templates/agents/agent_create.html
{% extends "base.html" %}

{% block title %}
 
Create Agent

{% endblock title %}

{% block content %}
    <h3><a href="{% url "agents:agents" %}">Go back</a </h3>
    <hr>
    <h1>Create a Agent</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" >Create Agent</button>
    </form>
        
{% endblock %}

agents/templates/agents/agent_list.html
{% extends "base.html" %}

{% block title %}
Agents List
{% endblock title %}

{% block content %}

    <section class="text-gray-600 body-font">
        <div class="container px-5 py-24 mx-auto flex flex-wrap">
            <div class="w-full mb-5 flex justify-between items-center border-b border-gray-200">
                <div>
                    <h1 class="text-4xl text-gray-800">Agents</h1>
                </div>
                <div>
                    <a href="{% url 'agents:agent_create'  %}"> Create Agent</a>
                </div>
            </div>
        
            <hr />
            <div class="flex flex-wrap -m-4">
            {% for agent in object_list %}
            <div class="p-4 lg:w-1/2 md:w-full">
                <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
                <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10" viewBox="0 0 24 24">
                    <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                    <circle cx="12" cy="7" r="4"></circle>
                    </svg>
                </div>
                <div class="flex-grow">
                    <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{ agent.name.username }}</h2>
                    <p class="leading-relaxed text-base">A short description abour the lead</p>
                    <a href="#" class="mt-3 text-indigo-500 inline-flex items-center">
                    View Lead
                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                        <path d="M5 12h14M12 5l7 7-7 7"></path>
                    </svg>
                    </a>
                </div>
                </div>
            </div>
            {% endfor %}
            
            </div>
        </div>
    </section>

{% endblock content %}